strict-sigcheck = false

[YouTube]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube.patches]
"github:MorpheApp/morphe-patches" = []

[YT-Music]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"

[YT-Music.patches]
"github:MorpheApp/morphe-patches" = []

[Reddit]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Reddit.patches]
"github:MorpheApp/morphe-patches" = []

[YouTube-Experimental]
enabled = false
brand = "morphe-dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
version = "exp"
patcher-args = "-e 'Change header' -Ocustom=icons/YouTube/header -e 'Custom branding' -OcustomIcon=icons/YouTube/branding -OcustomName='YouTube Morphe'"

[YouTube-Experimental.patches]
"github:MorpheApp/morphe-patches" = { version = "dev" }

[YT-Music-Experimental]
enabled = false
brand = "morphe-dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"
version = "exp"
patcher-args = "-e 'Change header' -Ocustom=icons/Music/header -e 'Custom branding' -OcustomIcon=icons/Music/branding -OcustomName='Music Morphe'"

[YT-Music-Experimental.patches]
"github:MorpheApp/morphe-patches" = { version = "dev" }

[Reddit-Experimental]
enabled = false
brand = "morphe-dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
version = "exp"
patcher-args = "-e 'Custom branding name for Reddit' -OappName='Reddit Morphe'"

[Reddit-Experimental.patches]
"github:MorpheApp/morphe-patches" = { version = "dev" }

[X-Twitter]
enabled = true
brand = "piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[X-Twitter.patches]
"github:crimera/piko" = ["Browse tweet object", "Dynamic color"]

[Instagram]
enabled = true
brand = "piko"
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
# uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"
patcher-args = "-e 'Theme' -Oamoled=true"

[Instagram.patches]
"github:crimera/piko" = []

[CamScanner]
enabled = false
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-information-co-ltd/camscanner-phone-pdf-creator/"
uptodown-dlurl = "https://camscanner.en.uptodown.com/android"
changelog-keywords = ["CamScanner"]

[CamScanner.patches]
"github:hoo-dles/morphe-patches" = []

[Duolingo]
enabled = false
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo/"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
changelog-keywords = ["Duolingo"]

[Duolingo.patches]
"github:hoo-dles/morphe-patches" = []

[Prime-Video]
enabled = false
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video/"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
arch = "arm64-v8a"
changelog-keywords = ["Prime Video"]

[Prime-Video.patches]
"github:hoo-dles/morphe-patches" = []

[SoundCloud]
enabled = false
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"
changelog-keywords = ["SoundCloud"]

[SoundCloud.patches]
"github:hoo-dles/morphe-patches" = []

[WPS-Office]
enabled = false
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/wps-software-pte-ltd/wps-office-pdf/"
uptodown-dlurl = "https://wps-office.en.uptodown.com/android"
changelog-keywords = ["WPS"]

[WPS-Office.patches]
"github:hoo-dles/morphe-patches" = []

[JioHotstar]
enabled = false
brand = "paresh"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/in.startv.hotstar"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/jiostar-india-private-limited/hotstar-2/"
changelog-keywords = ["JioHotstar"]

[JioHotstar.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Proton-VPN_paresh]
enabled = false
brand = "paresh"
app-name = "Proton VPN"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn/"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
changelog-keywords = ["Proton VPN"]

[Proton-VPN_paresh.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Telegram]
enabled = false
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram-web-version/"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"
changelog-keywords = ["Telegram"]

[Telegram.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Truecaller]
enabled = false
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block/"
uptodown-dlurl = "https://truecaller.en.uptodown.com/android"
changelog-keywords = ["Truecaller"]

[Truecaller.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

["1.1.1.1"]
enabled = false
brand = "rushi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet/"
uptodown-dlurl = "https://1-1-1-1.en.uptodown.com/android"
changelog-keywords = ["1.1.1"]

["1.1.1.1".patches]
"github:rushiranpise/morphe-patches" = []

[Proton-VPN_rushi]
enabled = false
brand = "rushi"
app-name = "Proton VPN"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn/"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
changelog-keywords = ["Proton VPN"]

[Proton-VPN_rushi.patches]
"github:rushiranpise/morphe-patches" = []

[InShot]
enabled = false
brand = "hooman"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshot-inc/inshot-video-editor-photo-editor/"
uptodown-dlurl = "https://inshot-editor.en.uptodown.com/android"
changelog-keywords = ["InShot"]

[InShot.patches]
"github:arandomhooman/hoomans-morphe-patches" = []

[Twitch]
enabled = false
brand = "hooman"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
changelog-keywords = ["Twitch"]

[Twitch.patches]
"github:arandomhooman/hoomans-morphe-patches" = []

[Amazon-Music]
enabled = false
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-music-discover-songs/"
uptodown-dlurl = "https://amazon-mp3.en.uptodown.com/android"

[Amazon-Music.patches]
"github:RookieEnough/De-Vanced" = []

[Disney-Plus]
enabled = false
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/disney/disney/"
uptodown-dlurl = "https://disney-disneyplus.en.uptodown.com/android"

[Disney-Plus.patches]
"github:RookieEnough/De-Vanced" = []

[Facebook]
enabled = false
brand = "de-vanced"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/com.facebook.katana"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
uptodown-durl = "https://facebook.en.uptodown.com/android"
arch = "both"

[Facebook.patches]
"github:RookieEnough/De-Vanced" = []

[Google-Photos]
enabled = false
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Google-Photos.patches]
"github:RookieEnough/De-Vanced" = []

[Messenger]
enabled = false
brand = "de-vanced"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/com.facebook.orca"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-technologies-llc/messenger/"
# uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
arch = "both"

[Messenger.patches]
"github:RookieEnough/De-Vanced" = []

[Threads]
enabled = false
brand = "de-vanced"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/com.instagram.barcelona"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app/"
# uptodown-dlurl = "https://threads.en.uptodown.com/android"
arch = "both"

[Threads.patches]
"github:RookieEnough/De-Vanced" = []

[TikTok]
enabled = false
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"

[TikTok.patches]
"github:RookieEnough/De-Vanced" = []

[Viber]
enabled = false
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/viber-media-s-a-r-l/viber/"

[Viber.patches]
"github:RookieEnough/De-Vanced" = []